### ISSUE TITLE
No ILFunc attribute

### ISSUE THREAD

**Issue by Affinity121** [Janiels/ILFunc#1]
I do not see it. Also please provide a message what exactly I have to write into "Pre-Build event command line".

**Comment by jakobbotsch** [comment]
The attribute can be any attribute named `ILFuncAttribute`. Its constructor should just take the IL string as the argument. This project is not supposed to be referenced by anything, only run as a separate pass after compilation.

For usage you can try invoking it without args - it should print how it is used. This tool was really just meant for my own use, and has some limitations (for example, it will probably break if the method you are replacing has other attributes on it). Another option, which is probably more mature, is at https://github.com/dotnet/corefxlab/tree/master/src/System.Slices/tools/ILSub.

**Comment by Affinity121** [comment]
C:\YourPathToILFunc\ILFunc.exe $(TargetPath) /debug
